# Generated by Django 4.2.7 on 2023-11-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SellAssist', '0008_alter_sellassistorder_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KauflandAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('clientkey', models.CharField(max_length=200)),
                ('secretkey', models.CharField(max_length=200)),
                ('stock_synchro', models.CharField(choices=[('1h', '1h'), ('4h', '4h'), ('8h', '8h'), ('24', '24h')], default='4h', max_length=10)),
                ('price_synchro', models.CharField(choices=[('1h', '1h'), ('4h', '4h'), ('8h', '8h'), ('24', '24h')], default='4h', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='KauflandAPICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now=True)),
                ('status_code', models.IntegerField()),
                ('has_error', models.BooleanField(default=False)),
                ('response', models.TextField()),
                ('method', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KauflandOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=20, null=True)),
                ('has_error', models.BooleanField(default=False)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('message', models.TextField(blank=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('marketplace', models.CharField(max_length=200, null=True)),
                ('toupdate', models.BooleanField(default=False)),
                ('id_product', models.CharField(max_length=200)),
                ('id_unit', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('new', 'NEW'), ('used_as_new', 'USED___AS_NEW')], default='new', max_length=20)),
                ('status', models.CharField(choices=[('available', 'AVAILVABLE'), ('onhold', 'ONHOLD')], default='available', max_length=20)),
                ('_listing_price', models.FloatField()),
                ('minimum_price', models.FloatField()),
                ('_amount', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('id_offer', models.CharField(max_length=50)),
                ('id_warehouse', models.CharField(max_length=20)),
                ('id_shipping_group', models.CharField(max_length=20)),
                ('storefront', models.CharField(choices=[('de', 'de'), ('sk', 'sk'), ('cz', 'cz')], max_length=2)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SellAssist.sellassistproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
