# Generated by Django 4.2.7 on 2023-11-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellAssistAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('home_number', models.CharField(max_length=200)),
                ('flat_number', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_nip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SellAssistAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('apikey', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SellAssistCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SellAssistPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('payment_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SellAssistPickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SellAssistProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200)),
                ('variant_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('ean', models.CharField(max_length=20, unique=True)),
                ('sku', models.CharField(max_length=20)),
                ('is_bundle', models.BooleanField(default=False)),
                ('bundle_id', models.IntegerField(default=0)),
                ('quantity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SellAssistShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('shipment_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SellAssistUnknownProduct',
            fields=[
                ('sellassistproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SellAssist.sellassistproduct')),
            ],
            bases=('SellAssist.sellassistproduct',),
        ),
        migrations.CreateModel(
            name='SellAssistOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(null=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('partial', 'partial'), ('excess', 'excess'), ('unknown', 'unknown')], default='unknown', max_length=10)),
                ('status', models.IntegerField()),
                ('date', models.CharField(max_length=200)),
                ('shipment_price', models.FloatField()),
                ('deadline', models.DateField()),
                ('important', models.BooleanField(default=False)),
                ('invoice', models.BooleanField(default=False)),
                ('document_number', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('external_id', models.CharField(max_length=200)),
                ('registered', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
                ('messages', models.TextField(blank=True, default=None, null=True)),
                ('tracking_num', models.CharField(default='', max_length=200)),
                ('marketplace', models.CharField(max_length=200)),
                ('bill_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_address', to='SellAssist.sellassistaddress')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SellAssist.sellassistpayment')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SellAssist.sellassistshipment')),
                ('shipment_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_address', to='SellAssist.sellassistaddress')),
            ],
        ),
        migrations.CreateModel(
            name='SellAssistCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('stock_update', models.BooleanField(default=True)),
                ('additional_information', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellAssist.sellassistorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SellAssist.sellassistproduct')),
            ],
        ),
        migrations.AddField(
            model_name='sellassistaddress',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SellAssist.sellassistcountry'),
        ),
    ]
