# Generated by Django 4.2.7 on 2023-11-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellAssist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellassistproduct',
            name='ean',
            field=models.CharField(max_length=20),
        ),
    ]
