# Generated by Django 4.2.7 on 2023-11-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellAssist', '0003_sellassistproductregistered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellAssistProductRegistered',
            new_name='SellAssistRegisteredProduct',
        ),
    ]
