# Generated by Django 4.2.7 on 2023-11-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellAssist', '0004_rename_sellassistproductregistered_sellassistregisteredproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellassistorder',
            name='external_id',
        ),
        migrations.AddField(
            model_name='sellassistorder',
            name='marketplace_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sellassistorder',
            name='sellassist_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
